name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Debug Context
      run: |
        echo ref_name "${{github.ref_name}}"
        echo ref_type "${{github.ref_type}}"
        echo event_name "${{github.event_name}}"
        echo head_ref "${{github.head_ref}}"
        echo base_ref "${{github.base_ref}}"
        echo action "${{github.action}}"
        

    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: install git-conventional-commits
      run: npm install --global git-conventional-commits
    - name: validate commits message
      run: git-conventional-commits commit-msg-hook git-conventional-commits.json
      
